### ISSUE TITLE
PalginNeoscryptMiner

### ISSUE THREAD

**Issue by nobitacu** [nemosminer/NemosMiner-v2.4.1#130]
Got this error at the end of its benchmarking... which then it does not switch to the next miner as it tries to in the end:

Get-Content : Cannot find path 'C:\NemosMiner-v2.3-2.3.1-Palgin\Wrapper_23333.txt' because it does not exist.
At C:\NemosMiner-v2.3-2.3.1-Palgin\Include.ps1:404 char:33
+                     $HashRate = Get-Content ".\Wrapper_$Port.txt"
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\NemosMiner-v...apper_23333.txt:String) [Get-Content], 
ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
Get-Content : Cannot find path 'C:\NemosMiner-v2.3-2.3.1-Palgin\Wrapper_23333.txt'
because it does not exist.
At C:\NemosMiner-v2.3-2.3.1-Palgin\Include.ps1:404 char:33
+                     $HashRate = Get-Content ".\Wrapper_$Port.txt"
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\NemosMiner-v...apper_23333.txt:St
   ring) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContent
   Command

Get-Content : Cannot find path 'C:\NemosMiner-v2.3-2.3.1-Palgin\Wrapper_23333.txt' because it does not exist.
At C:\NemosMiner-v2.3-2.3.1-Palgin\Include.ps1:406 char:82
+ ... Start-Sleep $Interval; $HashRate = Get-Content ".\Wrapper_$Port.txt"}
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\NemosMiner-v...apper_23333.txt:String) [Get-Content], 
ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
Get-Content : Cannot find path 'C:\NemosMiner-v2.3-2.3.1-Palgin\Wrapper_23333.txt'
because it does not exist.
At C:\NemosMiner-v2.3-2.3.1-Palgin\Include.ps1:406 char:82
+ ... Start-Sleep $Interval; $HashRate = Get-Content ".\Wrapper_$Port.txt"}
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\NemosMiner-v...apper_23333.txt:St
   ring) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContent
   Command

Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
Loading miners..

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner-v2.3/archive/2.3.1+Palgin.zip  

NemosMiner-v2.3.1+Palgin (New Miner testing)

**Comment by nemosminer** [comment]
I found a fix, looks ugly but works, replace the codes in Wrapper.ps1:
Code:
   $PowerShell.Streams.Verbose.ReadAll() | ForEach-Object {
        $Line = $_

        if ($Line -like "*total speed:*" -or $Line -like "*accepted:*") {
            $Words = $Line -split " "
            $HashRate = [Decimal]$Words[$Words.IndexOf(($Words -like "*/s" | Select-Object -Last 1)) - 1]

            switch ($Words[$Words.IndexOf(($Words -like "*/s" | Select-Object -Last 1))]) {
                "kh/s" {$HashRate *= [Math]::Pow(1000, 1)}
                "mh/s" {$HashRate *= [Math]::Pow(1000, 2)}
                "gh/s" {$HashRate *= [Math]::Pow(1000, 3)}
                "th/s" {$HashRate *= [Math]::Pow(1000, 4)}
                "ph/s" {$HashRate *= [Math]::Pow(1000, 5)}
            }

            $HashRate | Set-Content ".\Wrapper_$Id.txt"
        } elseif ($Line -like "*overall speed is*") {
            $Words = $Line -split " "
            $HashRate = [Decimal]($Words -like "*H/s*" -replace ',', '' -replace "[^0-9.]",'' | Select-Object -Last 1)

            switch ($Words -like "*H/s*" -replace "[0-9.,]",'' | Select-Object -Last 1) {
                "KH/s" {$HashRate *= [Math]::Pow(1000, 1)}
                "mH/s" {$HashRate *= [Math]::Pow(1000, 2)}
                "MH/s" {$HashRate *= [Math]::Pow(1000, 2)}
            }

            $HashRate | Set-Content ".\Wrapper_$Id.txt"
        }

        $Line
    }

**Comment by rtdegraaf** [comment]
FYI, I'm having the same issue while benchmarking with the PalginHSR miner. Removing it from the list with algo solve's te problem for now.

**Comment by nemosminer** [comment]
done testing and working now....

**Comment by nemosminer** [comment]
remove Palgin as not ready to be added yet

did manage to get it to work but not up to my standards
will continue trying and add it to following release

**Comment by bykka** [comment]
Just to keep all Palgin issues in one place.
My benchmarking for two 1080ti shows next 

```
 Palgin               NeoScrypt      310,24 MH/s      126,046      0,12605 125,393    1 482,295    0,40628 ahashpool24hr-
 CcminerKlaust        NeoScrypt        2,79 MH/s        1,133      0,00113 1,127         13,320    0,40628 ahashpool24hr-
```

**Comment by nemosminer** [comment]
@nemosminer alright, I see you use the APIs now, cool.

Palgin doesn't have an API, did you try casting Palgin's hashrate to an integer before saving? Palgin is so much faster for NeoScrypt, it's such a waste that it doesn't work right now.

just try $HashRate = [int]$HashRate before $HashRate | Set-Content ".\PalginNeoHashrate.txt"

**Comment by nemosminer** [comment]
All is well Palgin is added and running well

latest master code is now ready to run through 6x10603gb & 6x1080ti test rigs 

will post results in a hour or 2 if all is well v2.4.1 will be released

**Comment by nemosminer** [comment]
@TomaszDom thankyou very much, it worked well just needed to add a empty PalginNeoHashrate.txt
to prevent Red error from popping up saying it does not exist... the wrapper updates the PalginNeoHashrate.txt with current hashrate every time "overall speed" is displayed in HSR miner....

All is well Palgin is added and running well

latest master code is now ready to run through 6x10603gb & 6x1080ti test rigs

will post results in a hour or 2 if all is well v2.4.1 will be released

**Comment by nemosminer** [comment]
done https://github.com/nemosminer/NemosMiner-v2.4.1/commit/0f879648ac1f6495406c917a1739612faad797b9
