### ISSUE TITLE
new Alexis-Phi ccminer

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.4.1#189]
test on 6x1060 & 6x1080ti compare to current phi miner for improvements 

test all  algos for improvements

https://github.com/216k155/ccminer-phi-anxmod/releases

**Comment by Nateck** [comment]
VIRUS Inside !

**Comment by nemosminer** [comment]
ok i haven;t even tested it yet ... was going to today

**Comment by Sniffdog** [comment]
https://github.com/Sniffdog/Sniffdogminer/issues/78  

still no issues as of yet...

**Comment by nemosminer** [comment]
thanks 
just the same "false flag" as other 
miner is clean

**Comment by nemosminer** [comment]
Added for phi algo tested faster on my single 1070pc 

running through 6x10603gb & 6x1080ti rig now to confirm
