### ISSUE TITLE
Large rigs, is SelGPU really mandatory?

### ISSUE THREAD

**Issue by tonyaik** [nemosminer/NemosMiner-v2.4.1#190]
I currently have a 6GPU rig but I'm just waiting for parts for my last 5 cards which will bring it to 11 cards. How should I index the 11th card? Why is SelGPU mandatory (well, it defaults to 0,1 if you remove the arguments)? I think all miners defaults to all available GPUs if you don't specifically select any GPUs.

**Comment by nemosminer** [comment]
yes if you remove it will use all available devices 
i had alot of request from users to add -SelGPU so i did but for large mining rigs it is not needed and can be removed...

**Comment by tonyaik** [comment]
Yes, I understand why you would want it. But when I removed the argument it defaulted to pass 0,1 to the miner?

**Comment by nemosminer** [comment]
you also need to go into the "miners" folder 
edit: 
Nemosminer-v2.4.ps1 
find:
    [String]$SelGPUDSTM = "0 1",
    [Parameter(Mandatory=$false)]
    [String]$SelGPUCC = "0,1",

change to:
    [String]$SelGPUDSTM = "",
    [Parameter(Mandatory=$false)]
    [String]$SelGPUCC = "",

save:

**Comment by nemosminer** [comment]
if that does not work you will have to 

go into "miners" folder

edit: 
miner.ps1
you need to remove -d $SelGPUCC

eg. before:
$Commands = [PSCustomObject]@{
    "bitcore" = " -d $SelGPUCC --api-remote" #Bitcore
    #"jha" = " -d $SelGPUCC" #Jha
    #"blake2s" = " -d $SelGPUCC" #Blake2s
    #"blakecoin" = " -d $SelGPUCC" #Blakecoin
    #"vanilla" = "" #BlakeVanilla
    #"cryptonight" = " -d $SelGPUCC" #Cryptonight
    #"decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = "" #Groestl
    #"hmq1725" = " -d $SelGPUCC" #hmq1725
    #"keccak" = "" #Keccak
    "lbry" = " -d $SelGPUCC --api-remote" #Lbry
    #"lyra2v2" = "" #Lyra2RE2
    #"lyra2z" = " -d $SelGPUCC" #Lyra2z
    #"myr-gr" = "" #MyriadGroestl
    #"neoscrypt" = " -d $SelGPUCC" #NeoScrypt
    #"nist5" = "" #Nist5
    #"pascal" = "" #Pascal
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    #"sia" = "" #Sia
    #"sib" = "" #Sib
    #"skein" = "" #Skein
    "skunk" = " -d $SelGPUCC --api-remote" #Skunk
    #"timetravel" = " -d $SelGPUCC" #Timetravel
    #"tribus" = " -d $SelGPUCC" #Tribus
    #"x11" = "" #X11
    #"veltor" = "" #Veltor
    #"x11evo" = " -d $SelGPUCC" #X11evo
    #"x17" = " -d $SelGPUCC" #X17
    #"yescrypt" = "" #Yescrypt

eg: after:
$Commands = [PSCustomObject]@{
    "bitcore" = " --api-remote" #Bitcore
    #"jha" = "" #Jha
    #"blake2s" = "" #Blake2s
    #"blakecoin" = "" #Blakecoin
    #"vanilla" = "" #BlakeVanilla
    #"cryptonight" = "" #Cryptonight
    #"decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = "" #Groestl
    #"hmq1725" = "" #hmq1725
    #"keccak" = "" #Keccak
    "lbry" = " --api-remote" #Lbry
    #"lyra2v2" = "" #Lyra2RE2
    #"lyra2z" = "" #Lyra2z
    #"myr-gr" = "" #MyriadGroestl
    #"neoscrypt" = "" #NeoScrypt
    #"nist5" = "" #Nist5
    #"pascal" = "" #Pascal
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    #"sia" = "" #Sia
    #"sib" = "" #Sib
    #"skein" = "" #Skein
    "skunk" =  --api-remote" #Skunk
    #"timetravel" = "" #Timetravel
    #"tribus" = "" #Tribus
    #"x11" = "" #X11
    #"veltor" = "" #Veltor
    #"x11evo" = "" #X11evo
    #"x17" = "" #X17
    #"yescrypt" = "" #Yescrypt

**Comment by tonyaik** [comment]
Yep, thanks. I'm thinking that that might be the default behavior?

**Comment by tonyaik** [comment]
I can see if I can find a solution later. I'll let you know if I do
