### ISSUE TITLE
add ability to change api ports in bat file

### ISSUE THREAD

**Issue by jjude80** [nemosminer/NemosMiner-v2.4.1#192]
Through my experimenting, I have found that running nemosminer in multiple sessions (one for each card) staggered ,each with a 15 minute cycle time, is the most profitable way to run it.  That way you get your share percentage up all the way per algo, and you dont loose out on another algo if it goes most profitable.   I have doubled my daily usd by doing this. However it is irritating to edit each miners ps1 file each time a new version comes out.  I propose being able to change the api ports used via the bat file to make it easier.  that way someone unable to figure out how to edit the ps1 file properly can do this, and so that I dont have to have several full nemosminer folders configured.
![24hr balance image](https://user-images.githubusercontent.com/18168364/35174067-fce0f74e-fd3b-11e7-9ae6-4d79a5e2679e.png)

**Comment by nemosminer** [comment]
sure

**Comment by 8-cloud** [comment]
jjude80: Any chance to provide the instructions for multiple sessions?
Thanks
8C

**Comment by Agent21** [comment]
I'm not understand what you're saying @jjude80, what settings are you changing?

**Comment by jagauthier** [comment]
He most likely has different cards.  One card, like the 1080ti does really well algo <a>, but not as good with algo <b>. Then he has a 1070ti, which does well with algo<b> not not algo<a>.  So it makes sense for them to mine what each one is good at.

**Comment by Coinminer24** [comment]
Am trying to do this (as I have different cards) by changing API ports in the miner ps1 files; however, still getting problems where is says port in use. Going to try benchmarking separately and then marking files as read only before running.

**Comment by numb401** [comment]
+1 to this request. A note added to the readme for multiple instances would suffice as well. I run a 1060 and 1070ti and when benchmarking both (in different folders), their hashrates would go into the wrong stat folders and under the wrong algorithm due to the same port trying to be used by two instances of CCminer. 

The workaround is below at the bottom of each miners .ps1 file in the \Miners\ folder.:

`$Commands | Get-Member -MemberType NoteProperty | Select -ExpandProperty Name | ForEach {
    [PSCustomObject]@{
        Type = "NVIDIA"
        Path = $Path
        Arguments = "-a $_ -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_)"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week}
        API = "Ccminer"
        **Port = 4069**
        Wrap = $false
        URI = $Uri
    }
}`

**Comment by Coinminer24** [comment]
I just tried doing as suggest numb401 but for whatever reason it still reported wrong. You didn't have to change the port anywhere else?

**Comment by numb401** [comment]
@Coinminer24 After digging a little deeper, I found I had to add the port to the line that denotes the algorithm as follows: (Lines 6 and 7 of trpruvotcuda9) along with adding the changed port to the bottom. When the miner starts, you should no longer see the failure to bind port error.

$Commands = [PSCustomObject]@{
    "phi" = " -d $SelGPUCC --api-remote **-b 4069**" #Phi

**Comment by MrPlusGH** [comment]
NPlusMiner supports running multiple instances.
[https://github.com/MrPlusGH/NPlusMiner/releases](url)
