### ISSUE TITLE
limit gpu intensity

### ISSUE THREAD

**Issue by alant89** [nemosminer/NemosMiner-v2.4.1#195]
Is it possible to add a way to limit the intensity of the GPU's?

**Comment by nemosminer** [comment]
yes that can be done you can edit the selected "miner" .ps1 and change intensity to suit you

**Comment by srvsrv** [comment]
I can't find intensity parameter in miners .ps1 files? Can you help with this?

https://github.com/nemosminer/NemosMiner-v2.4.1/blob/master/Miners/CcminerAlexis78Phi.ps1

**Comment by Klexicon** [comment]
Just add -i <number> in between the quotes.  It's a Ccminer setting if you want to google to read up more on it.

**Comment by alant89** [comment]
Can it be made into a global setting that changes all the different miners?

**Comment by srvsrv** [comment]
i think that this is not good idea, because optimisation must be only for specific algo.. all algos need works diffrent
