### ISSUE TITLE
Switching at LOT more with 2.4 ?  Or am I just reading it wrong?

### ISSUE THREAD

**Issue by kevharper** [nemosminer/NemosMiner-v2.4.1#202]
I may just be reading the report on the Nemo on 2.4's 'new' CLI wrong but to me it looks like 2.4 is switching at lot more that 2.3?   I'm working on comparing the logs of the two versions.  I am running each for a few hours and then will post here so I can understand what I may be reading wrong.   I was thinking that 2.4 should switch a little less than 2.3 with the addition of -ActiveMinerGainPct.     

On a related note, would it be possible to have Nemo create a simplie report that only lists the coins/algos and run times of every switch in a simple, easy to read, list?

**Comment by 8-cloud** [comment]
I am also comparing 2.4.1 with 2.3 and AM, will let you know

**Comment by nemosminer** [comment]
switching has not been altered since 2.3... at all they will be the same v.2.4 and v.2.4.1 will switch less if you increase -ActiveMinerGainPct.

**Comment by kevharper** [comment]
OK.  Thank  you.  I think I just need to better understand how to read the log.   Or, maybe a simplified log can be created.  I really love your software!   

Attached is a copy of my latest log file.   What does the Cnt colum really mean?  

What would be really great is a running list of only Coin/Algo/Start/Stop/Duration.  Just a suggestion!

[miner.log](https://github.com/nemosminer/NemosMiner-v2.4.1/files/1650180/miner.log)

**Comment by nemosminer** [comment]
Cnt "simply means how many times the miner has run" short for count

**Comment by kevharper** [comment]
Thanks.  I figured that much.  But how many times since when?  For instance below.     I would expect the Cnt to be continually increasing for a given miner/algo but it seems to go up and down.

Thank you for taking your time to provide feedback.

> --------------------------------------------------------------------------------
Last Refresh: 01/21/2018 11:47:33
Sleep 30 sec
--------------------------------------------------------------------------------
Running:

    Speed Started  Active   Cnt Command
    ----- -------  ------   --- -------
6.19 MH/s 00:00:19 00:01:14 2   Bin\NVIDIA-CcminerKlaust\ccminer.exe -a neoscrypt -o
                                stratum+tcp://hub.miningpoolhub.com:17012 -u xxx.xxx -p x -d 0,1,2,3,4


Failed:  1

    Speed Exited   Active   Cnt  Command
    ----- ------   ------   ---  -------
0.00 PH/s 00:03:13 00:00:00 Once Bin\NVIDIA-DSTM\zm.exe --telemetry=127.0.0.1:2222 --server
                                 us-east.equihash-hub.miningpoolhub.com --port 17023 --user
                                 1QGADhdMRpp9Pk5u5zG1TrHKRrdK5R81TE.NemosMiner-v2.4 --pass x -d 0 1 2 3 4


--------------------------------------------------------------------------------
Last Refresh: 01/21/2018 11:48:03
Sleep 30 sec
--------------------------------------------------------------------------------
Stats ' NeoScrypt ' ->  6.19 MH after 1213 sec
--------------------------------------------------------------------------------
Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
Loading miners..
Idle:  2

    Speed Exited   Active   Cnt  Command
    ----- ------   ------   ---  -------
2.53 KH/s 00:00:51 00:05:24 3    Bin\NVIDIA-DSTM\zm.exe --telemetry=127.0.0.1:2222 --server
                                 us-east.equihash-hub.miningpoolhub.com --port 17023 --user xxx.xxx --pass
                                 x -d 0 1 2 3 4
2.83 GH/s 00:00:20 00:01:01 Once Bin\NVIDIA-Alexis78\ccminer-alexis.exe -a skein -o
                                 stratum+tcp://hub.miningpoolhub.com:17016 -u xxx.xxx -p x -d 0,1,2,3,4
                                 --api-remote


1BTC =  11589.78 USD

>

**Comment by kevharper** [comment]
One other questions....what is the difference between the 'Master' and a normal release?  Is the Master considered safe to use?

**Comment by nemosminer** [comment]
master is my latest code yes it safe to use (has PalginNeo  Enabled now)

its actually ready for release as v2.4.1 im just doing a full 24-48hour test run on my 6x10603gb and 6x1080ti

Before i release it....
