### ISSUE TITLE
XMRig (cryptonight) missing from 2.4.1 ?

### ISSUE THREAD

**Issue by kevharper** [nemosminer/NemosMiner-v2.4.1#205]
I noticed XMRig  was not downloaded with the initial run of 2.4.1 because I usually have to open the firewall for it once it launches.   Was there a reason for removing it?  I think it is an efficient miner.   Any particular reason it was removed?

**Comment by nemosminer** [comment]
it only worked on 1070.. i'll will do more testing and add it back to v2.4.2

**Comment by kevharper** [comment]
Thank you!  For your info, it also works on 970.  I have an old 970 I use with it to mine Electronium - 455 H/s or about 10 ETN per day with only about 60W consumption.
