### ISSUE TITLE
PalginHSR Neoscript Out of range exeption

### ISSUE THREAD

**Issue by Dobromir-Atanasov** [nemosminer/NemosMiner-v2.4.1#207]
Cannot convert value "12680000000000.00" to type "System.Int32". Error: "Value was either too
large or too small for an Int32."
At C:\NemosMiner-v2.4.1\Wrapper.ps1:57 char:4
+ $HashRate = [int]$HashRate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastIConvertible

I'm running your program on Rig with 10 cards and I'm getting the above error while running PalginHSR Neoscript.
First I faced a problem after benchmark. The shell was reporting huge numbers as a benchmark result (12 000 000 TH or something like that) as well as the above mentioned error (reported in PalginHSR window).
I've managed to fix the problem by editing both "PalginNeoHashrate.txt" in root folder and "PalginHSR_Neoscript_HashRate.txt" in stats folder by hand. Had to increase hashrates a bit, to prevent updating the results by the miner (not sure about the last).

P.S. Had to set "PalginNeoHashrate.txt" to ReadOnly, since it keep getting updated.

**Comment by nemosminer** [comment]
what 10 cards?

**Comment by Dobromir-Atanasov** [comment]
1070Ti they are giving ~1 268 000 hash/s each = ~12 680 000 hash/s combined
In the "PalginNeoHashrate.txt" the written number is "12680000000000.00" (after the benchmark). It seems that the miner gives incorrect information somehow. Even if I try to correct that number by hand after benchmark, once PalginHSR starts (i.e. Neoscrypt is most profitable algo) the number is getting updated with that big, incorrect number.

**Comment by Dobromir-Atanasov** [comment]
Maybe the hashrate is not parsed correctly?

**Comment by nemosminer** [comment]
what 10 cards, are you running? that hashrate looks huge...........

i have only tested myself with 6x1080ti as that is the biggest rigs i own....

**Comment by nemosminer** [comment]
yeh not sure i can't replicate this error i have have 2 6x1070ti rigs my self both passes benchmark flawlessly

**Comment by Dobromir-Atanasov** [comment]
I think I've found when the problem appears:
When the PalginHSR is reporting "overall speed is 12,68MH/s, efficiency 100%" your wrapper.ps1 is trying to handle value of "12680000000000.00" to type"System.In32"
I don't know how and where 12.68MH are converted to 12 680 000 000 000 but it seems is happening in the wrapper.ps1

**Comment by Dobromir-Atanasov** [comment]
cards are Inno3d nvidia 1070Ti, but they are not the problem I think, conversion from MH to full number is the problem imho.

**Comment by Dobromir-Atanasov** [comment]
Maybe this is the problem:

extracted from wrapper.ps1

$HashRate | Set-Content ".\PalginNeoHashrate.txt"
        } elseif ($Line -like "*overall speed is*") {
            $Words = $Line -split " "
            $HashRate = [Decimal]($Words -like "*H/s*" -replace ',', '' -replace "[^0-9.]",'' | Select-Object -Last 1)

            switch ($Words -like "*H/s*" -replace "[0-9.,]",'' | Select-Object -Last 1) {
                "KH/s" {$HashRate *= [Math]::Pow(1000, 1)}
                ## "mH/s" {$HashRate *= [Math]::Pow(1000, 2)}
                "MH/s" {$HashRate *= [Math]::Pow(1000, 2)}
            }
			$HashRate = [int]$HashRate
            $HashRate | Set-Content ".\PalginNeoHashrate.txt"
        }

**Comment by Dobromir-Atanasov** [comment]
I think when you are converting 12.68MH to 12 680 000 the scrypt powers 12.68 twice. But I'm not sure! I've only passed C# for beginners. :D

**Comment by nemosminer** [comment]
im not sure but it maybe any thing over 10mhs it can not handle try removing a card or two 
with -SelGPU to bring your hashrate to below 10mhs
re run benchmark making sure PalginNeoHasrate.txt is blank

**Comment by Dobromir-Atanasov** [comment]
It doesn't mater if PalginNeoHashrate.txt is blank or not, every time when PalginHSR is running Neoscrypt and report about "average hashrate is xxx" appears in the PalginHSR window, wrapper.ps1 is trying to parse the result and if it is reported in MH (for example 12.34 MH or 11.11MH) in conversion to a number with zeros instead of converting 12.34MH to 12340000 the number becomes 12340000000000.00 and if this number is bigger then the number already written in the PalginNeoHashrate.txt (for example if I have fixed the number by hand before that or if the file is blank) wrapper is updating the number with the one that is bigger and cant be handled in result in PalginNeoHashrate appears "12340000000000.00" instead of "12340000".

**Comment by Shotfire** [comment]
I have the same problem on 3 rigs with 7 1080ti's each. My test rig with 2 1080ti's it works fine.

Type: NVIDIA

Miner                Algorithm           Speed      mBTC/Day     BTC/Day        USD/Day BTC/GH/Day Pool
-----                ---------           -----      --------     -------        ------- ---------- ----
PalginHSR            NeoScrypt      10.95 TH/s 3,606,495.506 3,606.49551 40,201,605.405    0.32933 ahashpool-
CcminerTpruvotcuda9  Tribus        680.60 MH/s        11.067     0.01107        123.359    0.01626 ahashpool-
CcminerAlexis78Phi   Phi           233.30 MH/s         7.398     0.00740         82.466    0.03171 ahashpool-
ccminerpolytimos     X17           125.85 MH/s         7.026     0.00703         78.322    0.05583 ahashpool-
CcminerAlexis78cuda9 Xevan          41.99 MH/s         6.299     0.00630         70.216    0.15000 ahashpool-
ccminerpolytimos     Blake2s        50.23 GH/s         4.916     0.00492         54.795    0.00010 ahashpool-
ccminerpolytimos     Lyra2RE2      511.34 MH/s         4.883     0.00488         54.435    0.00955 ahashpool-
ccminerpolytimos     Nist5         581.13 MH/s         4.556     0.00456         50.787    0.00784 ahashpool-
ccminerpolytimos     Skein           6.85 GH/s         4.521     0.00452         50.395    0.00066 ahashpool-
CcminerTpruvot       Skunk         376.27 MH/s         4.485     0.00449         49.996    0.01192 ahashpool-
CcminerTpruvot       Bitcore       165.51 MH/s         3.380     0.00338         37.673    0.02042 ahashpool-
ccminerAlexis78      Hsr           147.83 MH/s         3.199     0.00320         35.660    0.02164 ahashpool-
ccminerpolytimos     C11           200.82 MH/s         2.828     0.00283         31.519    0.01408 ahashpool-
ccminerAlexis78      MyriadGroestl 873.21 MH/s         0.917     0.00092         10.220    0.00105 ahashpool-
ccminerpolytimos     Lbry            3.53 GH/s         0.672     0.00067          7.485    0.00019 ahashpool-
ccminerAlexis78      Sib           152.23 MH/s         0.422     0.00042          4.700    0.00277 ahashpool-

**Comment by nemosminer** [comment]
im not sure but it maybe any thing over 10mhs it can not handle try removing a card or two
with -SelGPU to bring your hashrate to below 10mhs
re run benchmark making sure PalginNeoHasrate.txt is blank
if this is confirmed i should be able to do something about that
my biggest rig atm is 6 x1080ti they at 75%tdp(175wat) making 1.61mhs each total =9.66mhs and it benchmarks fine...

**Comment by Shotfire** [comment]
nemosminer,  Thanks for the reply. I addressed that in my original post. With 7 1080ti's the hash_rate is incorrect. With two 1080Ti's everything is fine. Thanks
