### ISSUE TITLE
Windows power shell "issue"...

### ISSUE THREAD

**Issue by meyerbro** [nemosminer/NemosMiner-v2.4.1#208]
![screenshot 2018-01-22 17 44 32](https://user-images.githubusercontent.com/1686520/35235502-3635a226-ff9c-11e7-83f2-95cb603ae8db.png)
This seems to make the switch fail with the latest version. It's in the same situation for more than 10 min already, no switch and no update. I'm still in the "benchmark" phase, but stuck with this one because of this "Windows Power Shell" miner...

**Comment by zzup** [comment]
Check out https://github.com/nemosminer/NemosMiner-v2.4.1/issues/193

If you scroll down you will see that some cards need more time on the HSR for benchmarking.  You have to see the statement "overall speed is" before it will send it to the system.  On my 1070 ti I had to increase the default bench time just on HSR to 900 seconds.  Just bench neo algo by it self to get that one going.

**Comment by nemosminer** [comment]
wait the full 18mins.... for HSRNeo nothing i can do about that until Palgin adds a API to there Miner....

**Comment by meyerbro** [comment]
Thanks everyone.
