### ISSUE TITLE
PalginNeoscrypt miner not working

### ISSUE THREAD

**Issue by tr1l3r** [nemosminer/NemosMiner-v2.4.1#209]
Hi Nemo. Just tried to benchmark the new neoscrypt miner and it shows only rejected shares, on nvidia gtx 970 show 8Mhash, which is tottaly wrong and I can't seem to get it to work. Is it 970 that's causing a problem or does the miner have some issues? It is also redflagging 1070 and one 1060, while on the previous version 2.4 everything is running smootly. Thanx for your reply.

**Comment by nemosminer** [comment]
970 is not supported
