### ISSUE TITLE
poly algo update zpool

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.4.1#210]
Quote from: cr3moon on Today at 12:10:36 PM
   Type: NVIDIA

Miner                Algorithm            Speed     mBTC/Day      BTC/Day      USD/Day BTC/GH/Day Pool
-----                ---------            -----     --------      -------      ------- ---------- ----
ccminerpolytimos     X17             36.52 MH/s        1.577      0.00158       18.075    0.04319 zpool-
ccminerpolytimos     Skein            1.84 GH/s        1.382      0.00138       15.839    0.00075 zpool-
CcminerTpruvot       Skunk          104.03 MH/s        1.130      0.00113       12.945    0.01086 zpool-
CcminerTpruvot       Bitcore         55.74 MH/s        1.099      0.00110       12.590    0.01971 zpool-
ccminerpolytimos     poly          Benchmarking Benchmarking Benchmarking Benchmarking    0.00589 zpool-
CcminerTpruvotcuda9  Groestl       Benchmarking Benchmarking Benchmarking Benchmarking    0.00355 zpool-
DSTM                 Equihash      Benchmarking Benchmarking Benchmarking Benchmarking  573.61000 zpool-
PalginHSR            NeoScrypt     Benchmarking Benchmarking Benchmarking Benchmarking    0.41134 zpool-
CcminerTpruvotcuda9  X11evo        Benchmarking Benchmarking Benchmarking Benchmarking    0.02237 zpool-
CcminerTpruvotcuda9  Timetravel    Benchmarking Benchmarking Benchmarking Benchmarking    0.00314 zpool-
CcminerTpruvotcuda9  Tribus        Benchmarking Benchmarking Benchmarking Benchmarking    0.00048 zpool-
ccminerpolytimos     Nist5         Benchmarking Benchmarking Benchmarking Benchmarking    0.00930 zpool-
ccminerAlexis78      Sib           Benchmarking Benchmarking Benchmarking Benchmarking    0.00493 zpool-
CcminerAlexis78cuda9 Xevan         Benchmarking Benchmarking Benchmarking Benchmarking    0.06559 zpool-
ccminerAlexis78      MyriadGroestl Benchmarking Benchmarking Benchmarking Benchmarking    0.00030 zpool-
ccminerAlexis78      Blakecoin     Benchmarking Benchmarking Benchmarking Benchmarking    0.00002 zpool-
ccminerAlexis78      Hsr           Benchmarking Benchmarking Benchmarking Benchmarking    0.03283 zpool-
CcminerAlexis78Phi   Phi           Benchmarking Benchmarking Benchmarking Benchmarking    0.02448 zpool-
ccminerpolytimos     Lbry          Benchmarking Benchmarking Benchmarking Benchmarking    0.00020 zpool-
ccminerpolytimos     Lyra2RE2      Benchmarking Benchmarking Benchmarking Benchmarking    0.00630 zpool-
ccminerpolytimos     Keccak        Benchmarking Benchmarking Benchmarking Benchmarking    0.00014 zpool-
ccminerpolytimos     Blake2s       Benchmarking Benchmarking Benchmarking Benchmarking    0.00009 zpool-
ccminerpolytimos     C11           Benchmarking Benchmarking Benchmarking Benchmarking    0.02056 zpool-

Running:
Failed:  1

    Speed Exited   Active   Cnt  Command
    ----- ------   ------   ---  -------
0.00 PH/s dd:hh:mm 00:00:00 Once Bin\NVIDIA-ccminerpolytimos\ccminer.exe -a polytimos -o stratum+tcp://polytimos.mine.zpool.ca:8463 -u 14rEu3oaRyfF7z6R869rDL54dABUEza1Xz -p ID=NemosMiner-v2.4.1,c=BTC -d 0,1,2,3

--------------------------------------------------------------------------------
Last Refresh: 01/22/2018 05:48:35
Sleep 30 sec
--------------------------------------------------------------------------------

need help guys i tried everything i know and i cant figure out why i am getting this error. 
this rig has    2x1060 6gb   1x1070    1x1070ti 
Mining on zpool bat on latest release version 2.4.1 downloaded fresh copy again an hour ago 
benchmark for poly fails ....it opens the miner window and closes it right after

have been using nemosminer since 2.3 never had no issues even when i updated to pre-release versions or whenever i noticed nemo update the github i would download the latest update and never had any issues until now so thats why its really weird that this is happening

if i remove the algo from bat or turn off the polytimos in the miner then it just removes it from benchmarking and all is set with the rest

anyone know what might be causing this?

**Comment by NoKwarl** [comment]
I'm getting poly failing benchmark with window closed as well. Single gtx 1080ti.

**Comment by TeunJaspers** [comment]
Workaround is change in ccminerpolytimos.ps1:

Change line 16, alter polytimos into poly and it works :)

**Comment by TeunJaspers** [comment]
Turns out that this is not all, manually added stats else it keeps benchmarking. Probably broke the link between algorithm stats and miner with above workaround.

**Comment by nemosminer** [comment]
thanks i'll sort poly algo out today

**Comment by nemosminer** [comment]
Done Tested with zpool
