### ISSUE TITLE
Help with X17, (makes no sense) 

### ISSUE THREAD

**Issue by cmbconcretefire** [nemosminer/NemosMiner-v2.4.1#212]
I have 2 rigs. 6 x 1060 (6gb) and 6 x 1070 (8gb) 
EVERYTHING under the hood on both is exactly the same. Same PSU's, same Gpu's, same motherboards, same Ram. Same risers. Mining on the same pool > ahashpool. 

I added x17 to the bat file on my 1060 rig. It benchmarked fine, and I can confirm that it is switching algo's from time to time like neoscrypt, xvan, etc.....and then gets back around to x17 during good times. So it is working. 

So I decided to add x17 to my 1070 bat and it says it's benchmarking, the cmd window shows it's mining, but after 8 minutes ......it continues to say "benchmarking" and it never does translate into a USD daily earning stat. It's like it's getting hung up. I also have adjusted VM to the max possible on my hard drives. (Somewhere around 32+Gigs) < I have no more space for more. But if VM was an issue , it would affect the 1060 rig as well. (Same hard drives) I'm at a loss. Help.

**Comment by felipe-vvoosh** [comment]
Wait 18 min.

**Comment by Dobromir-Atanasov** [comment]
For 1070 (8GB) maximum VM you may need is 6 (number of cards) * 8,192GB (video memory) - 4GB (probably) RAM installed on computer ~ 45 GB
for 1060 (6GB) maximum VM is 6 * 6144 - 4GB ~32GB

**Comment by nemosminer** [comment]
64gb VM?
