### ISSUE TITLE
vector algo not being passed zpool stratum address

### ISSUE THREAD

**Issue by NoKwarl** [nemosminer/NemosMiner-v2.4.1#214]
See subject. Using 2.4.1. Happened in benchmarking, the miner is trying yo reach stratum+tcp:// with nothing else. Also it is the only algo not showing the pool in the benchmark table.

**Comment by cr3moon** [comment]
Remove veltor from bat file
Zpool dropped it

**Comment by nemosminer** [comment]
already have....
