### ISSUE TITLE
Add separate wallet for nicehash

### ISSUE THREAD

**Issue by geckah** [nemosminer/NemosMiner-v2.4.1#221]
is there a way to add a second wallet for those that mine into nicehash's internal wallet?

**Comment by jagauthier** [comment]
Can't you just specify the internal wallet address?

**Comment by nemosminer** [comment]
edit: startnicehash.bat
change    -Wallet 1QGADhdMRpp9Pk5u5zG1TrHKRrdK5R81TE   to your Nicehash wallet
save

**Comment by geckah** [comment]
Yes i know i could just add the internal wallet in the bat file, but i cant do that if i use nicehash as a backup pool.

Need a -nicewallet option or something
