### ISSUE TITLE
InvalidJsonException after crash

### ISSUE THREAD

**Issue by dangi12012** [nemosminer/NemosMiner-v2.4.1#222]
Every time my miner suddenly goes offline (plug power or crash) the nemosminer cannot start again. I always need to reinstall all files and do the benchmarks again. Other miners do not have this behaviour. 

Maybe dont leave the json file open and only have an active file handle while writing, or use Temp files?

**Comment by jagauthier** [comment]
Mine crashes multiple times daily, but I don't run into this issue very often. It could be that you are crashing as the file is being written.  To save benchmark cycles, just delete the newest profit files, and if those do not work, then the newest hashrate files.

**Comment by dangi12012** [comment]
Yeah no, robust software should be able to handle a crash. My miners are not really supervised so after an automatic restart after a crash i would expect everything to be working again.
Also I keep -Donate 24 on ;) 
So pls fix.

**Comment by nemosminer** [comment]
my donation is -donate 5.... 

your rigs should not be crashing.... if your rigs are crashing multi able times a day you need to fix your rigs...
