### ISSUE TITLE
X17 not working on miningpoolhub

### ISSUE THREAD

**Issue by dangi12012** [nemosminer/NemosMiner-v2.4.1#223]
When the miner tries to benchmark X17 on miningpoolhub CCminer outputs: Invalid Stratum URL: TCP://
The submitted mining URL is empty so this is definitely a bug as this does not happen in Nemosminer 2.3.

**Comment by dangi12012** [comment]
Oh I found it. In your Start.bat files there are algorithms that are not supported by the pool and the miner cannot deal with it - No Error message just infinite loop cannot connect. 
Fix please.

**Comment by nemosminer** [comment]
there is no x17 on miningpoolhub.............................
