### ISSUE TITLE
Benchmark re-writes are innacurate

### ISSUE THREAD

**Issue by jagauthier** [nemosminer/NemosMiner-v2.4.1#224]
Since updating to 2.4, benchmark speed rewrites are a total mess.  I keep having to delete/adjust them for different miners.

![image](https://user-images.githubusercontent.com/7101432/35447400-9c5976e0-0285-11e8-9421-dd5dbdb089dc.png)
![image](https://user-images.githubusercontent.com/7101432/35447451-c65a257a-0285-11e8-8c92-06317bba18b4.png)

**Comment by nemosminer** [comment]
im not getting that....
