### ISSUE TITLE
Whoops, looks like something went wrong to miningpoolhubstats.com 

### ISSUE THREAD

**Issue by grapikz** [nemosminer/NemosMiner-v2.4.1#227]
After encoding my wallet address to ahashpool I suddenly could not access miningpoolhubstats.com.
When I tried to sign-in it shows error " Whoops, looks like something went wrong".

Would you help me to rectify this issue?

I am using nemosminer.

Thanks in Advance.

**Comment by nemosminer** [comment]
miningpoolhubstats.com works for my rigs running NemosMiner... i just login at miningpoolhubstats.com added my miningpool API and Ahashpool Zpool BTC wallet address's and all my info came up.....
