### ISSUE TITLE
How to capture data from API ccminer?

### ISSUE THREAD

**Issue by Nateck** [nemosminer/NemosMiner-v2.4.1#228]
Hi guys, could someone let me know how to easly capture data from ccminer API using —api-remote or other command? Using POST command or something else?

**Comment by jagauthier** [comment]
it's a simple socket connection.  You can telnet to the port and type "threads", or "summary" and get data back.   The rest is up to you!

**Comment by Nateck** [comment]
Thanks man!

**Comment by Nateck** [comment]
Nope...is not working. Im using telnet, and is not possible to write any command. When Im connected on port (net stats shows me), I can't use keyboard, any pressed key closing telnet after connected. any solutions ?

**Comment by nemosminer** [comment]
-b 4069


 or similar
