### ISSUE TITLE
CCminer crashing

### ISSUE THREAD

**Issue by msonthineni** [nemosminer/NemosMiner-v2.4.1#230]
Hey nemosminer

Having something weird going on, sometimes ccminer crashes for me, when switching coins.  Happens randomly.

Not sure why this is happening.  Because some of the rigs I have don't experience this at all.  I have increased the page files on all rigs to 20000 so Its not a memory issue.  I have many coins well algorithms going so I'm not sure which coins are doing this.  And its very difficult to track it down.

I was wondering if you experienced this before or someone else has.  

Here is a picture of what is happening.  There really is no log info on this so kinda at a loss here.

I have tried dropping the intensity on the rigs that crash, but to no avail.

https://imgur.com/a/gu0GO

**Comment by msonthineni** [comment]
wait hmm seems like illegal memory access was encountered.  wasn't checking the miner logs, does does that mean?

**Comment by nemosminer** [comment]
Not sure why this is happening. Because some of the rigs I have don't experience this at all. I have increased the page files on all rigs to 20000 so Its not a memory issue. 

so thats 20gb you have it set at looks like your running 6x1070 or 6x1070ti? you will need at least 65gb of page file for those

**Comment by msonthineni** [comment]
I'm running 6 1070's per rig

this is the exact miner log crash

Cuda error in func 'skein512_cpu_setBlock_80' at line 1095 : an illegal memory access was encountered.

**Comment by nemosminer** [comment]
easy way to work it out is add your vram together eg. 6 x8gb =48gb minimum page file i recommend 64gb in my readme....

**Comment by msonthineni** [comment]
I might have upped them to 60gb actually, can't remember at the moment will check and let ya know :)

**Comment by msonthineni** [comment]
ah ok, they were set at 40gb, going to up to 50 and keep ya posted!

**Comment by msonthineni** [comment]
Yep it was the memory issue weird thought I changed all my virtual memory sizes, must have missed those 2 rigs, thanks for responses!
