### ISSUE TITLE
Klaust benchmark never ending

### ISSUE THREAD

**Issue by romulus5** [nemosminer/NemosMiner-v2.4.1#231]
I am running 4x 1080TIs. Everything benchmarks perfectly except for Klaust Neoscrypt miner. It seems to keep benchmarking forever. I've let it run for hours. 

![klaust](https://user-images.githubusercontent.com/35879902/35477106-5b645154-038a-11e8-9914-112741f49b23.jpg)

**Comment by nemosminer** [comment]
roger need to add api as its disabled by default now...

**Comment by romulus5** [comment]
Sorry, I am not a pro at this. You think you can help me add this api command?

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner-v2.4.1/commit/c1872379a071dcaddd853d6b2d8710e33e397773

**Comment by nemosminer** [comment]
NemosMiner-v2.4.1+latest commits 
https://github.com/nemosminer/NemosMiner-v2.4.1/archive/master.zip

**Comment by nemosminer** [comment]
fixed....

**Comment by romulus5** [comment]
Thanks bro, you rock!
