### ISSUE TITLE
Benchmark on MyriadGroestl never end

### ISSUE THREAD

**Issue by yepla** [nemosminer/NemosMiner-v2.4.1#232]
Hello,
I have try the v2.4.1 and benchmark on MyriadGroestl never end.
The mining start on MyriadGroestl but never finish :(

**Comment by nemosminer** [comment]
which pool?

**Comment by yepla** [comment]
miningpoolhub
but i have restart the benchmark before going to sleep and this time was Groestl algo never end

**Comment by yepla** [comment]
I have restart the miner and this time everything end correctly
