### ISSUE TITLE
Not possible to download miners on old versions of Nemo

### ISSUE THREAD

**Issue by srvsrv** [nemosminer/NemosMiner-v2.4.1#233]
There is problem downloading miners on old versions of nemo.

We have problems with the miners of new version, slow startup times etc.. but when we try to use old versions, there is an error in shell, which tells that there is not such file when downloading miners.

**Comment by numb401** [comment]
This is due to download links being changed from version to version. If you can find a valid link (take the link from current version of nemos) and replace the bad link in the /Miners/*.ps1 file, it will download the miner and work normally.

**Comment by srvsrv** [comment]
thanks 👍
