### ISSUE TITLE
Is there a solution hashrates to be updated only on benchmark?

### ISSUE THREAD

**Issue by srvsrv** [nemosminer/NemosMiner-v2.4.1#234]
Is there a solution hashrates to be updated only on benchmark?

The problem is, that now the hashrates are updated dynamic, not only on benchmark, also when mining after benchmark.

This causes bugs when sometimes miner is not closed, the hashrate from another algo is taken for not correct algo...

Also, when you have different GPU's and want to separate them in different miners, the hashrates become unreal... 

To reproduce the bug easy, just put nemos miner to mine for example on 1st GPU only, and start some external miner bat.. for example some ccminer to mine some algo.. you will sea that when hashrate is updated nemos SUM hashrate from the both miners without considering what is algo..

**Comment by nemosminer** [comment]
im not getting that bug...

**Comment by srvsrv** [comment]
I found only this:
to make all *hashrate files in /stats folder read only.. it's working for now, but when you make this there is red error in Nemos Miner
