### ISSUE TITLE
"Error Contacting pool, retrying......." Startzpool.bat

### ISSUE THREAD

**Issue by cryptoworld9016** [nemosminer/NemosMiner-v2.4.1#237]
Hi, i wanted to use zpool , i edited Startzpool.bat file , changed the address, specified number of GPUs along with all the algorithms needed for nvidia but as i start the batch file it say **"error contacting pool, retrying...."** i restarted my computer multiple times and the miner too ...but no fix .... please help ...
![whatsapp image 2018-01-30 at 12 45 34 am](https://user-images.githubusercontent.com/35606194/35557369-f25e4dd4-05ca-11e8-93a6-20c0d9bda3ed.jpeg)

**Comment by MrMineitall** [comment]
Im having the same issue if i use the 24hr bat... but the normal zpool works fine.. Ahash both normal and 24hr work fine as well... its only the zpool24hr.bat that is constantly failing to connect.

**Comment by cryptoworld9016** [comment]
I tried startzpool.bat file and it showed this error....What differenc does the 24hrs bat file makes?? 

Ar. Haresh Parmar

**Comment by cryptoworld9016** [comment]
i got this problem in the normal bat file ....i havnt tried the 24hrs bat file ....whats the difference between normal batch file and the 24hrs one????

**Comment by cryptoworld9016** [comment]
What u mean authored the thread ???? i didnt get it??
