### ISSUE TITLE
Retrieve latest coin currencies from api.nicehash instead of api.coinbase

### ISSUE THREAD

**Issue by axkman** [nemosminer/NemosMiner-v2.4.1#246]
Hi! 

I'm using nemosminer with nicehash account. The nicehash miner retrieves the recent coin values from api.nicehash but nemosminer retrieves it from api.coinbase. This way nemosminer will be miner best profitable coins based on coinbase values, but the nicehash values often differs from coinbase values.

Can you make an option so that nemosminer will retrieve the recent coin values from api.nicehash? So that it will start mining best profitable coins according to what are the most profitable according to nicehash?

Thank you!

(I think most people who are using nicehash account with nemosminer will be very happy with it!)

**Comment by nemosminer** [comment]
only btc rate is loaded from coinbase.... 

NiceHash API is used for algo price....
