### ISSUE TITLE
remove a xmrig commmand from source.

### ISSUE THREAD

**Issue by psionx** [nemosminer/NemosMiner-v2.4.1#249]
I would like to request the "--cuda-launch=" command be removed or you should at-least include instructions to change it in the readme file. as from my tests running the standalone exe it is not needed and causes the xmrig-nvidia.exe to crash when the wrong static numbers are picked.  
this happens in both 2.4.1 and 2.3 with a single gtx 1060 3gb when using miningpoolhub. 
your default 15x96=crash. 
xmrig default 44x27=works for now.

**Comment by jrafaelmdo** [comment]
@psionx 

Try this settings and see if performs better (it works great with all my cards 1080ti, 1070ti, 1060 6gb, 1050ti )

--cuda-launch=8x120 --cuda-bfactor=8 --cuda-bsleep=100 --keepalive --nicehash

**Comment by jrafaelmdo** [comment]
@psionx

CcminerTpruvotx64.ps1 works as good as XMRig and no fee.

I used the following launch command:  " -i 10.5 -l 8x120 --bfactor=8 -d $SelGPUCC --api-remote"

**Comment by nemosminer** [comment]
done
