### ISSUE TITLE
Support for Excavator, attached miner file for testing - Nvidia only

### ISSUE THREAD

**Issue by jrafaelmdo** [nemosminer/NemosMiner-v2.4.1#251]
I have created this file using parts of sniffdog and MPM code.

It works in all my systems Nvidia only ( 1 x 1080ti, 8 x 1060, 8 x 1070ti, 16 x 1050ti)

So far works very well (fastest at nist5, equihash, Lyra2re2 and neoScrypt) and since is the main miner used by nicehash it seems to be very actively develop.

Download and extract in miner folder. it should download the latest version by itself.

[ExcavatorNvidia.zip](https://github.com/nemosminer/NemosMiner-v2.4.1/files/1695752/ExcavatorNvidia.zip)

**Comment by nemosminer** [comment]
done
